<?php
    $response = [
        [
            'id' => 1,
            'marca' => 'Ford',
            'modello' => 'Fiesta',
            'carrozzeria' => 'berlina',
            'carburante' => 'Gas di petrolio liquefatto',
            'cilindrata' => 1388,
            'cavalli' => 97,
            'anno immatricolazione' => 2011,
            'trasmissione' => 'Manuale',
            'kilometri' => 157000,
            'colore' => "Bianco",
            'prezzo' => 4990.00,
            'accessori' => '<li> Alzacristalli elettrici </li> <li> Climatizzatore </li> <li> Controllo automatico clima </li> <li> Sensore di luminosità </li> <li> Sensore di pioggia </li> <li> Sistema di navigazione </li> <li> Specchietti laterali elettrici </li> <li> Vetri oscurati </li> <li> Volante in pelle </li> <li> Volante multifunzione </li> <li> Autoradio </li> <li> Bluetooth </li> <li> CD </li> <li> Computer di bordo </li> <li> MP3 </li> <li> USB </li> <li> Vivavoce </li> <li> Cerchi in lega </li> <li> Luce ambiente </li> <li> Pneumatici quattro stagioni </li> <li> Ruota di riserva </li> <li> Spoiler </li> <li> Tendalino </li> <li> ABS </li> <li> Airbag conducente </li> <li> Airbag laterali </li> <li> Airbag passeggero </li> <li> Antifurto </li> <li> Assistente abbaglianti </li> <li> Chiusura centralizzata </li> <li> Chiusura centralizzata telecomandata </li> <li> ESP </li> <li> Fari di profondità antiabbagliamento </li> <li> Fendinebbia </li> <li> Immobilizzatore elettronico </li> <li> Isofix </li> <li> Servosterzo </li>',
            'numero porte' => 5,
            'localita' => 'Firenze',
            'trazione' => 'Anteriore',
            'targa' => 'FH 876 LP',
            'immagine' => 'https://prod.pictures.autoscout24.net/listing-images/aa4f5506-e74b-48e7-b568-a9df3dcd589a_d2ab61ec-1fad-47c1-ab0f-a9c0d287172f.jpg/640x480.jpg',
            'neopatentato' => 'no'
        ],
        [
            'id' => 2,
            'marca' => 'Renault',
            'modello' => 'Captur',
            'carrozzeria' => 'suv',
            'carburante' => 'Benzina',
            'cilindrata' => 898,
            'cavalli' => 90,
            'anno immatricolazione' => 2014,
            'trasmissione' => 'Manuale',
            'kilometri' => 68000,
            'colore' => "Beige",
            'prezzo' => 11000.00,
            'accessori' => '<li> Alzacristalli elettrici </li> Climatizzatore </li> <li> Controllo automatico clima </li> <li> Sensore di luminosità </li> <li> Sensore di pioggia </li> <li> Sistema di navigazione </li> <li> Specchietti laterali elettrici </li> <li> Vetri oscurati </li> <li> Volante in pelle </li> <li> Volante multifunzione </li> <li> Autoradio </li> <li> Bluetooth </li> <li> CD </li> <li> Computer di bordo </li> <li> MP3 </li> <li> USB </li> <li> Vivavoce </li> <li> Cerchi in lega </li> <li> Luce ambiente </li> <li> Pneumatici quattro stagioni </li> <li> Ruota di riserva </li> <li> Spoiler </li> <li> Tendalino </li> <li> ABS </li> <li> Airbag conducente </li> <li> Airbag laterali </li> <li> Airbag passeggero </li> <li> Antifurto </li> <li> Assistente abbaglianti </li> <li> Chiusura centralizzata </li> <li> Chiusura centralizzata telecomandata </li> <li> ESP </li> <li> Fari di profondità antiabbagliamento </li> <li> Fendinebbia </li> <li> Immobilizzatore elettronico </li> <li> Isofix </li> <li> Servosterzo </li>',
            'numero porte' => 5,
            'localita' => 'Capannoli',
            'trazione' => 'Anteriore',
            'targa' => 'LP 156 FG',
            'immagine' => 'https://prod.pictures.autoscout24.net/listing-images/a70d3f24-f938-4a71-8792-cdfe653b0f0f_51fe2a6c-f788-48d1-922b-6cf0fd527863.jpg/640x480.jpg',
            'neopatentato' => 'si'
        ],
        [
            'id' => 3,
            'marca' => 'Volkswagen',
            'modello' => 'Golf',
            'carrozzeria' => 'berlina',
            'carburante' => 'Diesel',
            'cilindrata' => 1968,
            'cavalli' => 116,
            'anno immatricolazione' => 2021,
            'trasmissione' => 'Manuale',
            'kilometri' => 9203,
            'colore' => "Grigio",
            'prezzo' => 26500.00,
            'accessori' => '<li> Alzacristalli elettrici </li> Climatizzatore </li> <li> Controllo automatico clima </li> <li> Sensore di luminosità </li> <li> Sensore di pioggia </li> <li> Sistema di navigazione </li> <li> Specchietti laterali elettrici </li> <li> Vetri oscurati </li> <li> Volante in pelle </li> <li> Volante multifunzione </li> <li> Autoradio </li> <li> Bluetooth </li> <li> CD </li> <li> Computer di bordo </li> <li> MP3 </li> <li> USB </li> <li> Vivavoce </li> <li> Cerchi in lega </li> <li> Luce ambiente </li> <li> Pneumatici quattro stagioni </li> <li> Ruota di riserva </li> <li> Spoiler </li> <li> Tendalino </li> <li> ABS </li> <li> Airbag conducente </li> <li> Airbag laterali </li> <li> Airbag passeggero </li> <li> Antifurto </li> <li> Assistente abbaglianti </li> <li> Chiusura centralizzata </li> <li> Chiusura centralizzata telecomandata </li> <li> ESP </li> <li> Fari di profondità antiabbagliamento </li> <li> Fendinebbia </li> <li> Immobilizzatore elettronico </li> <li> Isofix </li> <li> Servosterzo </li>',
            'numero porte' => 5,
            'localita' => 'Torino',
            'trazione' => 'Anteriore',
            'targa' => null,
            'immagine' => 'https://prod.pictures.autoscout24.net/listing-images/d9977e21-bbb6-481b-b45d-46a3056ac74a_8f22e68d-63fa-472c-9ea9-b66fdc5f60b7.jpg/640x480.jpg',
            'neopatentato' => 'no'
        ],
        [
            'id' => 4,
            'marca' => 'Hyundai',
            'modello' => 'i20',
            'carrozzeria' => 'berlina',
            'carburante' => 'GPL',
            'cilindrata' => 1248,
            'cavalli' => 77,
            'anno immatricolazione' => 2009,
            'trasmissione' => 'Manuale',
            'kilometri' => 190000,
            'colore' => "Bianco",
            'prezzo' => 2900.00,
            'accessori' => '<li> Alzacristalli elettrici </li> Climatizzatore </li> <li> Controllo automatico clima </li> <li> Sensore di luminosità </li> <li> Sensore di pioggia </li> <li> Sistema di navigazione </li> <li> Specchietti laterali elettrici </li> <li> Vetri oscurati </li> <li> Volante in pelle </li> <li> Volante multifunzione </li> <li> Autoradio </li> <li> Bluetooth </li> <li> CD </li> <li> Computer di bordo </li> <li> MP3 </li> <li> USB </li> <li> Vivavoce </li> <li> Cerchi in lega </li> <li> Luce ambiente </li> <li> Pneumatici quattro stagioni </li> <li> Ruota di riserva </li> <li> Spoiler </li> <li> Tendalino </li> <li> ABS </li> <li> Airbag conducente </li> <li> Airbag laterali </li> <li> Airbag passeggero </li> <li> Antifurto </li> <li> Assistente abbaglianti </li> <li> Chiusura centralizzata </li> <li> Chiusura centralizzata telecomandata </li> <li> ESP </li> <li> Fari di profondità antiabbagliamento </li> <li> Fendinebbia </li> <li> Immobilizzatore elettronico </li> <li> Isofix </li> <li> Servosterzo </li>',
            'numero porte' => 5,
            'localita' => 'Caltanisetta',
            'trazione' => 'Anteriore',
            'targa' => 'DE 204 ZZ',
            'immagine' => 'https://prod.pictures.autoscout24.net/listing-images/cf46fb16-4b4b-44f6-bb8d-4c29146c2556_1d74d15f-8d04-41f0-abd6-62adf1a546de.jpg/640x480.jpg',
            'neopatentato' => 'si'
        ],
        [
            'id' => 5,
            'marca' => 'Suzuki',
            'modello' => 'Splash',
            'carrozzeria' => 'carrello',
            'carburante' => 'Benzina',
            'cilindrata' => 1050,
            'cavalli' => 65,
            'anno immatricolazione' => 2009,
            'trasmissione' => 'Manuale',
            'kilometri' => 160000,
            'colore' => "Grigia",
            'prezzo' => 4200.00,
            'accessori' => '<li> Alzacristalli elettrici </li> Climatizzatore </li> <li> Controllo automatico clima </li> <li> Sensore di luminosità </li> <li> Sensore di pioggia </li> <li> Sistema di navigazione </li> <li> Specchietti laterali elettrici </li> <li> Vetri oscurati </li> <li> Volante in pelle </li> <li> Volante multifunzione </li> <li> Autoradio </li> <li> Bluetooth </li> <li> CD </li> <li> Computer di bordo </li> <li> MP3 </li> <li> USB </li> <li> Vivavoce </li> <li> Cerchi in lega </li> <li> Luce ambiente </li> <li> Pneumatici quattro stagioni </li> <li> Ruota di riserva </li> <li> Spoiler </li> <li> Tendalino </li> <li> ABS </li> <li> Airbag conducente </li> <li> Airbag laterali </li> <li> Airbag passeggero </li> <li> Antifurto </li> <li> Assistente abbaglianti </li> <li> Chiusura centralizzata </li> <li> Chiusura centralizzata telecomandata </li> <li> ESP </li> <li> Fari di profondità antiabbagliamento </li> <li> Fendinebbia </li> <li> Immobilizzatore elettronico </li> <li> Isofix </li> <li> Servosterzo </li>',
            'numero porte' => 5,
            'localita' => 'Parma',
            'trazione' => 'Anteriore',
            'targa' => 'DZ 568 EL',
            'immagine' => 'https://prod.pictures.autoscout24.net/listing-images/d3e88af1-09ca-4cd6-be25-e54967556c11_0146482d-397a-4357-b666-c25718b1ff1f.jpg/640x480.jpg',
            'neopatentato' => 'si'
        ],
    ];
?>